version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_data:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    depends_on:
      - mongo

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: front
    volumes:
      - ./front:/front
    working_dir: /front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  mongo_data:

